### ISSUE TITLE
How 'terms' are related to KB

### ISSUE THREAD

**Issue by chenwuperth** [EagleW/PaperRobot#1]
Just wondering if/how 'terms' are related to head_entity_relation_tail_entity in the underlying KB at all? Thanks!

**Comment by EagleW** [comment]
Hi @chenwuperth, thank you very much for your interest in our research. After we used the entity mention extraction and linking system to extract important entities from the title, we will use those mentions to find their corresponding head or tail entities in the enhanced Knowledge base which is enhanced by the link prediction result. Those related head or tails and the extracted mentions together formed our terms for each pair of training, valid, or testing data.

**Comment by HFYSGQ** [comment]
After you extract entities and relationships from the reference topic, how do you find the relevant head or tail nodes in the enhanced knowledge map? How do you define the relevance? What is the method used?

**Comment by EagleW** [comment]
So I did the link prediction (which is in the github existing paper reading) over all entities in the knowledge graph and choose the top 10 mentions as the relevant entites

**Comment by EagleW** [comment]
Then we used all those triples as an enhanced knowledge graph

**Comment by HFYSGQ** [comment]
Thank you for your prompt reply, I got it！

**Comment by EagleW** [comment]
Hope you have a great day!
