### ISSUE TITLE
How many epoches do you use in these two tasks?

### ISSUE THREAD

**Issue by GabrielLin** [EagleW/PaperRobot#14]
Could you please share your training parameters in the training? How much time do you use? Thanks.

**Comment by EagleW** [comment]
For the first task, I use 2 weeks. For the second task, I use 1 week

**Comment by GabrielLin** [comment]
For the first task. I have to set batch size at 32 in order to run on TITAN RTX.
I train about 1 week and have finished  8 epochs.

> Epoch 8
> 27365 batches processed. current train batch loss: 1.062468

Is it normal? Thanks.

**Comment by EagleW** [comment]
I think it's normal
