### ISSUE TITLE
Training part of the dataset

### ISSUE THREAD

**Issue by am-h** [EagleW/PaperRobot#15]
Thanks for this great work! Since I have trouble regarding the memory, even when using GPU p100 and reducing the batch size. 
I want to know if I can train on a small set of the dataset. ? I could not exactly understand the part where loading the train_set.

Many thanks

**Comment by EagleW** [comment]
@am-h Thank you very much for your interest in our research. Which part of the code did you run? The writing part or the link prediction part?

**Comment by EagleW** [comment]
For paper reading, the data are loaded on LinkPredictionDataset, you can try to include part of the train2id.txt, valid2id.txt. Also, you can reduce the batch size by adding --batch_size 2 after python train.py. 
For paper writing,  the data are loaded on AssembleMem, you can try to change line 83 and line 86 of New paper writing/loader/preprocessing.py by truncating the data. You can reduce the batch size by adding --batch_size 2 after python train.py.
