### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'paper_reading/relation2id.txt

### ISSUE THREAD

**Issue by gitfans5** [EagleW/PaperRobot#19]
How to fix the error "FileNotFoundError: [Errno 2] No such file or directory: 'paper_reading/relation2id.txt"? Thanks.

**Comment by EagleW** [comment]
Hi @gitfans5  Thank you for your interest in our research. Please follow the [instructions](https://github.com/EagleW/PaperRobot#preprocessing) to download the [paper reading dataset](https://drive.google.com/open?id=1DLmxK5x7m8bDPK5ZfAROtGpkWZ_v980Z). Feel free to email me if you have any other questions.

**Comment by gitfans5** [comment]
Thank you for your reply. But I got a new error "networkx.exception.NetworkXError: Node 13593 in nodelist is not in G". So how to fix it? Thanks.

**Comment by EagleW** [comment]
Can you share your screenshot with me?

**Comment by pccai** [comment]
NetworkX version not matched

**Comment by OliveS9** [comment]
Which version of NetworkX does your package need? Thanks.

**Comment by EagleW** [comment]
@OliveS9 Please check https://github.com/EagleW/PaperRobot#pacakges

**Comment by EagleW** [comment]
The networkx is [NetworkX 2.3](https://networkx.github.io/documentation/stable/install.html)
