### ISSUE TITLE
How to generate KGs?

### ISSUE THREAD

**Issue by Tramac** [EagleW/PaperRobot#2]
Hi, thanks for your interesting work! I want to know where is the code of generating KGs?

**Comment by EagleW** [comment]
@Tramac Thank you for your interest in our work, I will release the new paper reading soon

**Comment by Tramac** [comment]
Thank you.

**Comment by EagleW** [comment]
Sorry, the code is pretty messy. So I'm still organizing them

**Comment by Tramac** [comment]
Understand.
