### ISSUE TITLE
Questions about code and paper_reading dataset

### ISSUE THREAD

**Issue by novice03** [EagleW/PaperRobot#21]
Hello, how do you use the model trained in existing paper reading for new paper writing? I understand that, for each title, you extract the top 10 related entities from the enriched knowledge graph. Where is the code corresponding to this? I don't see the GATA model being used in the code for new paper writing. Did you already run the model and save the results in `paper_reading.zip`? Also, can you please explain how you created the `paper_reading` dataset?

**Comment by 1754699523** [comment]
> Hello, how do you use the model trained in existing paper reading for new paper writing? I understand that, for each title, you extract the top 10 related entities from the enriched knowledge graph. Where is the code corresponding to this? I don't see the GATA model being used in the code for new paper writing. Did you already run the model and save the results in `paper_reading.zip`? Also, can you please explain how you created the `paper_reading` dataset?

Hello, have you figured this out? I have the same question

**Comment by mShining** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
