### ISSUE TITLE
PubTator-MeSH-CTD

### ISSUE THREAD

**Issue by OXPHOS** [EagleW/PaperRobot#3]
Hi there,

Congrats on the excellent accomplishment of PaperRobot! I saw that you are going to release more codes in the next few days. However, just out of curiosity, I am wondering whether the following is the workflow for KG generation?

    1. Perform NER with PubTator API
    2. Match Gene(NCBI), Disease(MEDIC) and chemicals to MeSH IDs
    3. Establish relations between entities by looking up CTD data.

FYI, when are the codes of the KG part expected to be released (if there's a plan)?

Thanks! :)

**Comment by EagleW** [comment]
Hi @OXPHOS , Thank you very much for your interest in our research. Yes, also after step 3, we also did link prediction on the existing KG. I will release the code and resource for the KG part this week.
