### ISSUE TITLE
Are new entities formed or just links?

### ISSUE THREAD

**Issue by Hanlin-Zhu** [EagleW/PaperRobot#6]
Hi! Thanks for the great work! Very enlightening tools! Looking forward to your release of old paper reading part soon. <p></p>So I am trying to understand how paperRobot generate new knowledge, and according to the Introduction section, it does so by forming new links between existing entities. Those entities are selected from publicly annotated medical literature datasets (CTD and PubTator). However in Table 1. It is noted that bold letter words like RT-PCT, western blotting represents "topically related entities". In Section 3.5 it is further noted that those two terms are the product of link prediction, But when I search RT-PCR or western blotting in CTD or PubTator though, they are not identified as previously labeled entities. So I am a bit confused whether terms like RT-PCR or western blotting are inside the enriched knowledge graph (which should only contain new links, not new entities?)  as new entities or not? If they are not, why would link prediction results in the creation of new ideas like them? I am quite new to the field so I apologize if the question seems trivial but it would be great if you could shed some light on this. Thanks!

**Comment by EagleW** [comment]
Hi @Hanlin-Zhu Thank your interest in our work. Sorry for the confusion. Acutally, RT-PCR and western blot are not entities in the link prediction, as you can check in the publicly avaliable Pubmed term, abstract, conclusion, title dataset(https://drive.google.com/open?id=1O91gX2maPHdIRUb9DdZmUOI5issRMXMY) . So what we mean is that through the link prediction, it introduces new entites such as  "nasopharyngeal_carcinoma", "diallyl_disulfide", which help the new paper writing model to generate the related ideas such as “RT-PCR” and “western blot”.

**Comment by Hanlin-Zhu** [comment]
Ok, that makes sense now. Thanks!
