### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.int32.

### ISSUE THREAD

**Issue by Beaujor** [EagleW/PaperRobot#8]
hi, when I train Existing paper reading, get follow error, can you help me?
Traceback (most recent call last):
  File "D:/PyCharmProjects/PaperRobot-master/Existing paper reading/train.py", line 101, in <module>
    graph, _ = load_graph(os.path.join(args.data_dir, 'train2id.txt'), num_ent)
  File "D:\PyCharmProjects\PaperRobot-master\Existing paper reading\utils\utils.py", line 93, in load_graph
    adj = torch.FloatTensor(nx.adjacency_matrix(graph.G, nodelist=range(num_ent)).todense())
TypeError: can't convert np.ndarray of type numpy.int32. The only supported types are: float64, float32, float16, int64, int32, int16, int8, and uint8.

**Comment by Beaujor** [comment]
@EagleW

**Comment by Beaujor** [comment]
OS is Windows7

**Comment by EagleW** [comment]
Could you try ubuntu? I have no trouble running on ubuntu 18.04. Also have you used the pytorch 1.10@Beaujor  https://user-images.githubusercontent.com/14304965/61386626-3022a780-a8e7-11e9-97e4-4f7d25672036.png

**Comment by EagleW** [comment]
Also I think the problem might relate to your pytorch version. The current pytorch supports creating tensor from numpy int 32.
https://pytorch.org/docs/stable/tensors.html#torch.Tensor
https://pytorch.org/docs/stable/tensors.html

**Comment by Beaujor** [comment]
Thanks，I'll try Ubuntu.发自我的华为手机-------- 原始邮件 --------主题：Re: [EagleW/PaperRobot] TypeError: can't convert np.ndarray of type numpy.int32. (#8)发件人：Qingyun Wang 收件人：EagleW/PaperRobot 抄送：Beaujor ,Author Could you try ubuntu? I have no trouble running on ubuntu 18.04. Also have you used the pytorch 1.10@Beaujor  https://user-images.githubusercontent.com/14304965/61386626-3022a780-a8e7-11e9-97e4-4f7d25672036.png

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/EagleW/PaperRobot/issues/8?email_source=notifications\u0026email_token=ABPZQBMALKFN2L2C27KFAB3QA36R7A5CNFSM4IGDS4CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TBFVA#issuecomment-514200276",
"url": "https://github.com/EagleW/PaperRobot/issues/8?email_source=notifications\u0026email_token=ABPZQBMALKFN2L2C27KFAB3QA36R7A5CNFSM4IGDS4CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TBFVA#issuecomment-514200276",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by EagleW** [comment]
Great!

**Comment by Beaujor** [comment]
i use the torch of version 1.1.0.i debug the error,  but find it in networkx.发自我的华为手机-------- 原始邮件 --------主题：Re: [EagleW/PaperRobot] TypeError: can't convert np.ndarray of type numpy.int32. (#8)发件人：Qingyun Wang 收件人：EagleW/PaperRobot 抄送：Beaujor ,Mention Also I think the problem might relate to your pytorch version. The current pytorch supports creating tensor from numpy int 32.
https://pytorch.org/docs/stable/tensors.html#torch.Tensor
https://pytorch.org/docs/stable/tensors.html

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/EagleW/PaperRobot/issues/8?email_source=notifications\u0026email_token=ABPZQBJRXO66VQH2KLXFAMTQA364VA5CNFSM4IGDS4CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TBNFA#issuecomment-514201236",
"url": "https://github.com/EagleW/PaperRobot/issues/8?email_source=notifications\u0026email_token=ABPZQBJRXO66VQH2KLXFAMTQA364VA5CNFSM4IGDS4CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TBNFA#issuecomment-514201236",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by EagleW** [comment]
Have you found the same issue on ubuntu, because some packages might work properly on windows?

**Comment by Beaujor** [comment]
also I try the current torch, thank you very much.发自我的华为手机-------- 原始邮件 --------主题：Re: [EagleW/PaperRobot] TypeError: can't convert np.ndarray of type numpy.int32. (#8)发件人：Qingyun Wang 收件人：EagleW/PaperRobot 抄送：Beaujor ,Mention Also I think the problem might relate to your pytorch version. The current pytorch supports creating tensor from numpy int 32.
https://pytorch.org/docs/stable/tensors.html#torch.Tensor
https://pytorch.org/docs/stable/tensors.html

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/EagleW/PaperRobot/issues/8?email_source=notifications\u0026email_token=ABPZQBJRXO66VQH2KLXFAMTQA364VA5CNFSM4IGDS4CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TBNFA#issuecomment-514201236",
"url": "https://github.com/EagleW/PaperRobot/issues/8?email_source=notifications\u0026email_token=ABPZQBJRXO66VQH2KLXFAMTQA364VA5CNFSM4IGDS4CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TBNFA#issuecomment-514201236",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by EagleW** [comment]
Another problem with windows is that they have a different path format. Therefore, it is possible that you model didn't take in the dataset properly

**Comment by EagleW** [comment]
@Beaujor https://www.howtogeek.com/181774/why-windows-uses-backslashes-and-everything-else-uses-forward-slashes/  You need to rewrite all paths in both train.py and test.py if you want to run it properly on windows

**Comment by Beaujor** [comment]
when I debug, the paths correct, but the data of graph converted to ndarray, the error found.发自我的华为手机-------- 原始邮件 --------主题：Re: [EagleW/PaperRobot] TypeError: can't convert np.ndarray of type numpy.int32. (#8)发件人：Qingyun Wang 收件人：EagleW/PaperRobot 抄送：Beaujor ,Mention @Beaujor https://www.howtogeek.com/181774/why-windows-uses-backslashes-and-everything-else-uses-forward-slashes/  You need to rewrite all paths in both train.py and test.py if you want to run it properly on windows

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/EagleW/PaperRobot/issues/8?email_source=notifications\u0026email_token=ABPZQBOEQY3XDWCTAQSZWYTQA4CKBA5CNFSM4IGDS4CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TEGDI#issuecomment-514212621",
"url": "https://github.com/EagleW/PaperRobot/issues/8?email_source=notifications\u0026email_token=ABPZQBOEQY3XDWCTAQSZWYTQA4CKBA5CNFSM4IGDS4CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TEGDI#issuecomment-514212621",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by EagleW** [comment]
@Beaujor Sorry currently I cannot give you any advice because I cannot reproduce the error. Maybe tomorrow when you try your program on ubuntu, if you encounter any problem I can give you some advice.

**Comment by Beaujor** [comment]
发自我的华为手机-------- 原始邮件 --------主题：Re: [EagleW/PaperRobot] TypeError: can't convert np.ndarray of type numpy.int32. (#8)发件人：Qingyun Wang 收件人：EagleW/PaperRobot 抄送：Beaujor ,Mention I'm creating the envs on Ubuntu, so don't have found the issue.Have you found the same issue on ubuntu, because some packages might work properly on windows?

**Comment by EagleW** [comment]
Great! Hope you have a great week!

**Comment by Beaujor** [comment]
yeah, thank you verymuch.发自我的华为手机-------- 原始邮件 --------主题：Re: [EagleW/PaperRobot] TypeError: can't convert np.ndarray of type numpy.int32. (#8)发件人：Qingyun Wang 收件人：EagleW/PaperRobot 抄送：Beaujor ,Mention @Beaujor Sorry currently I cannot give you any advice because I cannot reproduce the error. Maybe tomorrow when you try your program on ubuntu, if you encounter any problem I can give you some advice.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/EagleW/PaperRobot/issues/8?email_source=notifications\u0026email_token=ABPZQBJZIPOCXIZCAUCBZT3QA4EIRA5CNFSM4IGDS4CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TF2CQ#issuecomment-514219274",
"url": "https://github.com/EagleW/PaperRobot/issues/8?email_source=notifications\u0026email_token=ABPZQBJZIPOCXIZCAUCBZT3QA4EIRA5CNFSM4IGDS4CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TF2CQ#issuecomment-514219274",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Beaujor** [comment]
it run correctly on Ubuntu.发自我的华为手机-------- 原始邮件 --------主题：Re: [EagleW/PaperRobot] TypeError: can't convert np.ndarray of type numpy.int32. (#8)发件人：Qingyun Wang 收件人：EagleW/PaperRobot 抄送：Beaujor ,Mention Closed #8.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/EagleW/PaperRobot/issues/8?email_source=notifications\u0026email_token=ABPZQBNWZXEZODTZ32TZI5LQA4FBHA5CNFSM4IGDS4CKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSUZVX5I#event-2503171061",
"url": "https://github.com/EagleW/PaperRobot/issues/8?email_source=notifications\u0026email_token=ABPZQBNWZXEZODTZ32TZI5LQA4FBHA5CNFSM4IGDS4CKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSUZVX5I#event-2503171061",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by EagleW** [comment]
Great!
