### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.int32. 

### ISSUE THREAD

**Issue by shuziP** [EagleW/PaperRobot#9]
I run \Existing paper reading\train.py as described in the document
But something went wrong

Traceback (most recent call last):
  File "C:/Users/Desktop/PaperRobot-master/PaperRobot-master/Existing paper reading/train.py", line 101, in <module>
    graph, _ = load_graph(os.path.join(args.data_dir, 'train2id.txt'), num_ent)
  File "C:\Users\shuzip\Desktop\PaperRobot-master\PaperRobot-master\Existing paper reading\utils\utils.py", line 93, in load_graph
    adj = torch.FloatTensor(nx.adjacency_matrix(graph.G, nodelist=range(num_ent)).todense())
TypeError: can't convert np.ndarray of type numpy.int32. The only supported types are: float64, float32, float16, int64, int32, int16, int8, and uint8.

**Comment by EagleW** [comment]
Thank you for your interest! Unfortunately, the program cannot be running under windows environment as I mentioned in a previous closed issue. Please run the program under Ubuntu. Sore for the inconvenience.

**Comment by shuziP** [comment]
Thank you very much for your answer. I have successfully run the program with OS

**Comment by EagleW** [comment]
Great!
